### ISSUE TITLE
"Adauga in Cos" failed

### ISSUE THREAD

**Issue by MartoriiLuiSoare** [sebiboga/atestersmindset4#10]
**Environment**: Live
URL: https://www.emag.ro/placa-video-gigabyte-geforce-rtx-2070-windforce-2x-8g-8gb-gddr6-256-bit-gv-n2070wf2-8gd/pd/D1T415BBM/
Browser: Opera

**Steps to reproduce**:
1. open URL in browser
2. click on "Adauga in Cos"

**Expected results**:
"Produsul a fost adaugat cu succes in cos" message box pops up

**Actual results**:
"Produs indisponibil" message is displayed

**Comment by sebiboga** [comment]
this is just a DEMO
closing the bug
