### ISSUE TITLE
"Subscribe to newsletter" failed

### ISSUE THREAD

**Issue by MartoriiLuiSoare** [sebiboga/atestersmindset4#4]
**Environment**: QA
URL: http://abc.com
Browser: Chrome

**Steps to reproduce**:
1. open URL in browser
2. click on "Subscribe to newsletter"
3. submit email

**Expected results**:
"thank you for subscribing!" message is seen

**Actual results**:
404 error message is displayed

**Comment by sebiboga** [comment]
this is just a DEMO issue
closing the bug
