### ISSUE TITLE
"Add another account" failed

### ISSUE THREAD

**Issue by MartoriiLuiSoare** [sebiboga/atestersmindset4#7]
**Environment**: QA
URL: http://google.com/
Browser: Chrome

**Steps to reproduce**:
1. open URL in browser
2. log in to an existing google account
3. click on "Google account" button
4. click on "Add another account"

**Expected results**:
"Sign in" box is displayed

**Actual results**:
"Google cannot add another account at this time" message is displayed

**Comment by sebiboga** [comment]
this is just a DEMO issue
closing the bug
