### ISSUE TITLE
"Exploration" page failed to open

### ISSUE THREAD

**Issue by MartoriiLuiSoare** [sebiboga/atestersmindset4#8]
**Environment**: QA
URL: https://www.reddit.com/explore
Browser: Microsoft Edge

**Steps to reproduce**:
open URL in browser

**Expected results**:
Exploration page opens

**Actual results**:
"page not found.the page you requested does not exist" message is displayed

**Comment by sebiboga** [comment]
this is just for DEMO
closing the bug
