### ISSUE TITLE
"Edit intro" failed

### ISSUE THREAD

**Issue by MartoriiLuiSoare** [sebiboga/atestersmindset4#9]
**Environment**: Live
URL: https://www.linkedin.com/in/user/
Browser: Chrome

**Steps to reproduce**:
1. open URL in browser
2. log in user info
3. click on "Edit intro" button

**Expected results**:
"Edit intro" box pops up

**Actual results**:
"Something went wrong" message is displayed

**Comment by sebiboga** [comment]
this is just a DEMO
closing the bug
